### ISSUE TITLE
com.sidooo.ufile.exception.UFileServiceException: invalid signature (Service: UFile; RequestId: 0; Message: invalid signature)

### ISSUE THREAD

**Issue by coolsnow77** [sidooo/ucloud-sdk-java#3]
当采用UFileClient->putObject 带有contentType 参数请求时，报告签名错误.  不采用contentType 时。 上传文件时OK 的。 请问是不是putObject contentType 签名有问题？

**Comment by analyst004** [comment]
我检查一下

**Comment by coolsnow77** [comment]
谢谢。

**Comment by analyst004** [comment]
@coolsnow77  
1. 已经增加了contentType的类型检查
2. putObject(File)的时候可以不用指定contentType了， 会自动根据文件后缀名进行识别
3. putObject(File, ContentType) 仍然支持， 如果自动识别ContentType不能满足要求， 可以使用该接口。但用户指定的contentType必须在在mime.types的列表中
4. 增加了相关单元测试， 并已经在我本机运行通过。

**Comment by coolsnow77** [comment]
好的，谢谢, 请问我可以再mvn 中拉取到？

**Comment by analyst004** [comment]
还不能 我过会提1.4版本到中央库 

    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：kimzhang@sidooo.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master
On 06/08/2018 12:44, clsw77 wrote: 好的，谢谢, 请问我可以再mvn 中拉取到？

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/sidooo/ucloud-sdk-java/issues/3#issuecomment-395645298","url":"https://github.com/sidooo/ucloud-sdk-java/issues/3#issuecomment-395645298","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sidooo/ucloud-sdk-java","title":"sidooo/ucloud-sdk-java","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sidooo/ucloud-sdk-java"}},"updates":{"snippets":[{"icon":"PERSON","message":"@coolsnow77 in #3: 好的，谢谢, 请问我可以再mvn 中拉取到？ "}],"action":{"name":"View Issue","url":"https://github.com/sidooo/ucloud-sdk-java/issues/3#issuecomment-395645298"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [sidooo/ucloud-sdk-java] com.sidooo.ufile.exception.UFileServiceException: invalid signature (Service: UFile; RequestId: 0; Message: invalid signature) (#3)",
"sections": [
{
"text": "",
"activityTitle": "**clsw77**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@coolsnow77",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sidooo/ucloud-sdk-java\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sidooo/ucloud-sdk-java/issues/3#issuecomment-395645298"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343785402\n}"
}
],
"themeColor": "26292E"
}

**Comment by analyst004** [comment]
1.4 已经Release， 静等中央库同步。
如果着急用， 可以将git clone, 然后mvn install。
